# Generated by Django 3.2.3 on 2021-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_alter_service_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_graduate', models.DateField()),
                ('date_expired', models.DateField()),
                ('school', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('active', 'active'), ('dead', 'dead')], default='active', max_length=10)),
            ],
        ),
    ]
