# Generated by Django 3.2.3 on 2021-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_status_char_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sale_amount',
            field=models.FloatField(default=0),
        ),
    ]
